fido2/ctap2.py
https://fidoalliance.org/specs/fido-v2.0-ps-20170927/fido-client-to-authenticator-protocol-v2.0-ps-20170927.html#message-encoding
> Likewise, because some authenticators are memory constrained, the maximum message size supported by an authenticator may be limited. By default, authenticators must support messages of at least 1024 bytes. Authenticators may declare a different maximum message size supported using the maxMsgSize authenticatorGetInfo result parameter. Clients, platforms, and servers must not send messages larger than 1024 bytes unless the authenticator's maxMsgSize indicates support for the larger message size. Authenticators may return the CTAP2_ERR_REQUEST_TOO_LARGE error if size or memory constraints are exceeded.
=> maxMsgSize should default to 1024 bytes

fido2/client.py
self.ctap.get_info was removed in 1edb0d9d.  _ctap2_make_credential
was updated, but _ctap2_get_assertion wasn't.
=> fido2/client.py: fix _ctap2_get_assertion

examples/server/server.py, fido2/server.py, test/test_server.py
Define an object for a relying party to be used in server API.
Having defined object in API is more strict solution which prevents errors in typos when compared to passing a dictionary. It may also provide further validation and other functions.
Also the functions from `rpid` module may be converted to methods of `RelyingParty` class.
=> Define relying party object

fido2/attestation.py
In cases where an attestation is packed and does not contain an `x5c`, `PackedAttestation` incorrectly creates an instance of the `CoseKey` base class.
This PR fixes the bug by correctly calling `CoseKey.parse(...)` to instantiate the appropriate `CoseKey` subclass.
=> Bugfix: PackedAttestation.verify should call CoseKey.parse(...)

fido2/attestation.py
From the current version of the WebAuthn spec (emphasis mine):
> If the related attestation root certificate is used for multiple authenticator models, the Extension OID 1.3.6.1.4.1.45724.1.1.4 (id-fido-gen-ce-aaguid) MUST be present, containing the AAGUID as a 16-byte OCTET STRING. **The extension MUST NOT be marked as critical.**
=> Add extra attestation certificate check from spec

fido2/server.py, test/test_server.py
`Fido2Server.authentication_complete` may raise `InvalidSignature` from cryptography library. I wrap this exception into a `ValueError` which is returned in all other error cases.
=> Wrap invalid signature in authentication

fido2/server.py
introduced in the spec on 2019/07/31
see: https://github.com/w3c/webauthn/pull/1244
see: https://github.com/w3c/webauthn/issues/1235
=> implement FIDO AppID Exclusion Extension

README.adoc, fido2/_pyu2f/__init__.py, fido2/_pyu2f/freebsd.py, setup.py, test/_pyu2f/freebsd_test.py, test/_pyu2f/linux_test.py, test/_pyu2f/macos_test.py
Includes unit tests.
This also adds _pytest-runner_, so that unit tests can be excluded based on platform in _conftest.py_ easily (_pyfakefs_ isn't available for FreeBSD).
Tested with yubico/yubikey-manager (ykman fido ...).
I copied the google license headers to the new files in __pyu2f_. Code is formatted to pass _pycodestyle_ (existing files in __pyu2f_ use some custom formatting).
=> Add FreeBSD support

setup.py
that PEP 508 is supported.
See #65
=> Check if setuptools 20.2 or newer is installed, to verify

fido2/server.py
Added option to specify a custom challenge for `Fido2Server.authenticate_begin` method. 
This provides the same functionality as the current Yubico U2F library's [`U2FSignRequest` class as seen here.](https://github.com/Yubico/python-u2flib-server/blob/4b9d353a3ba82be40c6cf9bab39d34ea7e07cb5a/u2flib_server/model.py#L458)
=> Added custom challenge option to Fido2Server

setup.py
Hi, I just run into `ValueError: invalid version number '41.6.0.post20191030'` with setuptools 41.6.0 (conda distribution). This can fix it, I think loose version comparison would be good enough. 
Thanks
=> fix setuptools version incompatibility

fido2/_pyu2f/__init__.py, fido2/_pyu2f/openbsd.py, test/_pyu2f/openbsd_test.py
Support for OpenBSD in python-fido2 is heavily inspired on by libfido2's OpenBSD
support.
Tested on OpenBSD-current
As a note, `libusbhid` is an OpenBSD-specific library that's installed by default, so we can depend on it being on the system.
=> Add support for OpenBSD

fido2/_pyu2f/hidtransport.py
The `ToWireFormat` function of `InitPacket` currently uses a fixed report size of 64 instead of the report size obtained from the HID device's report descriptor, which makes the `python-fido2` library incompatible with devices with non-standard report sizes. This commit makes it compatible by reusing the `packet_size` dependent logic from `ContPacket`.
=> Use the advertised report size for INIT packets

fido2/_pyu2f/macos.py
I ran into this situation on my Mac when `__init__` failed before obtaining a handle. In that case, the newly-constructed object would have no `device_handle` attribute.
When the time comes to destroy the object, `__del__` assumes that `self.device_handle` exists. That causes the following unhelpful user-facing error:
```
$ ykman fido info
Exception ignored in: <function MacOsHidDevice.__del__ at 0x10702b4c0>
Traceback (most recent call last):
File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/fido2/_pyu2f/macos.py", line 469, in __del__
self.device_handle,
AttributeError: 'MacOsHidDevice' object has no attribute 'device_handle'
[…]
Error: Failed connecting to YubiKey 5 [OTP+FIDO+CCID]. Make sure the application have the required permissions.
```
One possible …
=> macOS: add early return to __del__

fido2/_pyu2f/macos.py, test/_pyu2f/test_macos.py
This PR improves macOS compatibility by changing the key used for accessing USB HID entries from a character-based path to a unique unsigned 64-bit number.
There is a [well-documented shortcoming](https://github.com/signal11/hidapi/issues/301) in the way macOS’s IOKit manages IORegistry entries. This causes USB HID entries to be [inaccessible by path](https://developer.apple.com/documentation/iokit/1514229-ioregistryentrygetpath?language=objc) if their IORegistry path length is [512 bytes](https://developer.apple.com/documentation/kernel/io_string_t?language=objc) or more.
Path lengths over 512 bytes have become more common. With current Macs now supporting external GPUs and Thunderbolt 3 chains, more and more intermediate nodes have been introduced into the IO tree, causing registry …
=> macOS: add support for ≥512-byte IO registry paths

examples/get_info.py, fido2/hid/__init__.py, fido2/hid/base.py, fido2/hid/freebsd.py, fido2/hid/linux.py, fido2/hid/macos.py, fido2/hid/openbsd.py, fido2/hid/windows.py, fido2/pcsc.py
I tried to add product name and serial number support to the internal descriptor for USB HID devices. If there is something similar for NFC devices it might be possible to add it, as well.
Tested in following environments:
- Linux (Ubuntu 20.10, python3): OK (product name contains manufacturer)
- Windows (Windows 10, python3): OK
- MacOSX (Catalina, python3): OK
- OpenBSD (6.8, python3): OK (Note:there have been changes in `struct usb_device_info`, see [OpenBSD bug mailing list](https://marc.info/?t=161565009600001&r=1&w=2). I don't know how this can be addressed to support older versions, too.)
- FreeBSD (12.2, python3): OK (serial number support needs updated uhid-freebsd, see grembo/uhid-freebsd#1; fragmented CTAP messages did not work in my VM setup, but seems unrelated)
=> USB HID: add product name and serial to descriptor.

fido2/hid/linux.py
The changes of #113 left trailing zeroes in the serial number and product name on Linux.
The `ioctl()` for retrieving the attributes returns the string length on success. Use the returned value to retrieve strings of the correct length.
=> Linux: remove trailing zeroes from serial

fido2/hid/freebsd.py, setup.py
This is a first draft version to be discussed.
As a side effect, `serial_number` support is enabled immediately for FreeBSD, too.
As a second side effect, no more C compilation is needed during FreeBSD install.
I've only tested on FreeBSD 12.2 amd64, so far. Seems to work. But I can only run very simple tests, as fragmented packets still don't work in my setup.
I tried to keep the structure as close as possible to the existing code for now.
=> FreeBSD: remove dependency on uhid-freebsd.

fido2/hid/linux.py
Instead of waiting for someone to fix an issue for me I thought, why don't I just do it myself?
Fixes https://github.com/Yubico/python-fido2/issues/127
=> Linux: Fail gracefully on invalid HIDIOCGRAWUNIQ

fido2/client.py, fido2/ctap2/pin.py
This allows instantiation of the ClientPin class on devices which do not support passing a client PIN. This is needed since the addition of getting a UV token allows usage without requiring PIN.
=> Handle authenticators with UV that do not support ClientPin.

tests/test_attestation.py
This is the case on RHEL9, and possibly other distros.
=> Skip TPM attestation test if SHA1 is unsupported.

examples/server/README.adoc, examples/server/server/server.py, fido2/rpid.py, fido2/server.py
Chromium-based browsers do not allow WebAuthn calls on https URLs that have certificate issues.
See https://lists.w3.org/Archives/Public/public-webauthn/2022Nov/0135.html
Changing this to http on localhost, which is considered a secure context in most browsers.
See https://groups.google.com/a/chromium.org/g/blink-dev/c/RC9dSw-O3fE/m/E3_0XaT0BAAJ
=> allow http://localhost origins

fido2/rpid.py, tests/test_rpid.py
Most browsers support subdomains of localhost as a secure context. We should too.
=> Allow localhost subdomains

examples/resident_key.py, fido2/client.py, fido2/utils.py, tests/test_client.py, tests/test_webauthn.py
This PR fixes the CBOR serialization which caused problems when using `webauthn_json_mapping` with the Fido2Client in certain cases, and corrects the behavior of dataclass constructors when passing dict values.
=> Fix webauthn_json_mapping behavior

tests/test_attestation.py
Drop extra call to attestation.verify()
Follow up to #194
=> "is" comparison fails with _Reasons.UNSUPPORTED_HASH, use "=="

examples/cred_blob.py, examples/credential.py, examples/large_blobs.py, examples/prf.py, examples/resident_key.py, fido2/client.py, fido2/ctap2/extensions.py, fido2/pcsc.py
This refactors extensions and the Fido2Client class to be able to support more complex extensions, such as evalByCredential in PRF.
=> Support PRF evalByCredential

fido2/hid/macos.py
Occassionally `CFRunLoopInMode()` returns `K_CF_RUN_LOOP_RUN_HANDLED_SOURCE` even though the `_hid_read_callback()` has not been invoked, resulting in reading from an empty queue. We can handle this by re-running the run loop with a retry mechanism.
=> Handle empty queue after `K_CF_RUN_LOOP_RUN_HANDLED_SOURCE`
